name: Build and push sbf

on:
  push:
    branches: ['dev/rewrite']
    paths:
      - 'sbf/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./sbf
          file: ./sbf/Dockerfile
          push: true
          tags: |
            houbystudio/sbf:latest
            houbystudio/sbf:${{ github.sha }}
          cache-from: type=registry,ref=houbystudio/sbf:buildcache
          cache-to: type=registry,ref=houbystudio/sbf:buildcache,mode=max
